// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Lae8X2TXELKpLml6z642FMVk6FOuImM',
    appId: '1:947309718023:web:81d9ac0735404f992b58a2',
    messagingSenderId: '947309718023',
    projectId: 'kazi-connect-e7856',
    authDomain: 'kazi-connect-e7856.firebaseapp.com',
    storageBucket: 'kazi-connect-e7856.firebasestorage.app',
    measurementId: 'G-W9EPJ9VFCG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1EufEf_YL5uaHmWj39F5q6EgZHQnplCo',
    appId: '1:947309718023:android:f22fc5bb9eeea4b42b58a2',
    messagingSenderId: '947309718023',
    projectId: 'kazi-connect-e7856',
    storageBucket: 'kazi-connect-e7856.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCORfz8Z7WXve9cQKDfRF2DqNa_u07Qy9E',
    appId: '1:947309718023:ios:9e2da79ffb086b0e2b58a2',
    messagingSenderId: '947309718023',
    projectId: 'kazi-connect-e7856',
    storageBucket: 'kazi-connect-e7856.firebasestorage.app',
    iosBundleId: 'com.example.homeLink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCORfz8Z7WXve9cQKDfRF2DqNa_u07Qy9E',
    appId: '1:947309718023:ios:9e2da79ffb086b0e2b58a2',
    messagingSenderId: '947309718023',
    projectId: 'kazi-connect-e7856',
    storageBucket: 'kazi-connect-e7856.firebasestorage.app',
    iosBundleId: 'com.example.homeLink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD3Lae8X2TXELKpLml6z642FMVk6FOuImM',
    appId: '1:947309718023:web:073842c3216b337c2b58a2',
    messagingSenderId: '947309718023',
    projectId: 'kazi-connect-e7856',
    authDomain: 'kazi-connect-e7856.firebaseapp.com',
    storageBucket: 'kazi-connect-e7856.firebasestorage.app',
    measurementId: 'G-PSDRSNHGED',
  );
}
